FROM centos
RUN yum install -y java 
VOLUME /tmp 
ADD Users/SDPB18/Documents/workspace/SpringProy/microservice/build/libs/microservice-0.0.1-SNAPSHOT.jar app,jar
RUN sh -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
